# Generated by Django 6.1 on 2026-08-21 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.IntegerField()),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('descricao', models.CharField(max_length=10)),
                ('realizada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacoes', to='crebitos.cliente')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['cliente', '-id'], name='idx_transacao_extrato')],
            },
        ),
    ]
