"""
Django settings for kernel project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r7=#10dos0*%(ws$)_ld2akp!my&mc*lzs8czc5mcb+_wb)g%u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Atrás do load balancer o Host chega como o nome do serviço (api01/api02) ou o
# IP do container. Validar isso não protege nada aqui e custa uma comparação por
# request — e um mismatch derrubaria a API inteira com 400.
ALLOWED_HOSTS = ['*']


# Application definition

# HACK DA RINHA: tudo que não serve aos dois endpoints do contrato está
# comentado em vez de apagado, para ficar visível o tamanho do corte.
# Ver `.claude/docs/05-hacks-da-competicao.md`, seção Infraestrutura.
INSTALLED_APPS = [
    # 'django.contrib.admin',         # painel administrativo — não existe rota
    # 'django.contrib.auth',          # usuários e permissões — API sem autenticação
    # 'django.contrib.contenttypes',  # só é exigido por auth e admin
    # 'django.contrib.sessions',      # não há sessão; nada é guardado entre requests
    # 'django.contrib.messages',      # framework de mensagens de template
    # 'django.contrib.staticfiles',   # não servimos nenhum arquivo estático
    'crebitos',
]

# HACK DA RINHA: middleware é custo pago em TODO request, ida e volta. Nenhum
# destes participa do contrato. Os dois mais caros de manter seriam o de sessão
# (que consultaria o banco) e o de CSRF (que rejeitaria nossos POSTs sem token).
MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',        # HSTS/redirect SSL — atrás do LB, sem TLS
    # 'django.contrib.sessions.middleware.SessionMiddleware', # sessão por request; exige o app sessions
    # 'django.middleware.common.CommonMiddleware',            # APPEND_SLASH, ETag, User-Agent banidos
    # 'django.middleware.csrf.CsrfViewMiddleware',            # CSRF barraria todo POST da carga
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',  # request.user — nunca lido
    # 'django.contrib.messages.middleware.MessageMiddleware',     # mensagens de template
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',   # header X-Frame-Options
]

ROOT_URLCONF = 'kernel.urls'

# HACK DA RINHA: nenhuma resposta é HTML. O motor de templates nunca é acionado.
TEMPLATES = []

WSGI_APPLICATION = 'kernel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# HACK DA RINHA: não há senhas — `django.contrib.auth` está desligado.
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# HACK DA RINHA: desligado. Com USE_I18N ligado, o Django ativa a maquinaria de
# tradução (LocaleMiddleware, gettext, negociação de idioma) em cada request.
USE_I18N = False

USE_TZ = True


# HACK DA RINHA: não servimos estáticos.
# STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# HACK DA RINHA: a API não envia e-mail.
# MAILERS = {
#     'default': {'BACKEND': 'django.core.mail.backends.console.EmailBackend'},
# }
