-- GERADO por scripts/gerar-sql.sh — não edite à mão.
-- Fonte da verdade: as migrations do Django em django/crebitos/migrations/.
-- Regenere com: just gen-sql

--
-- PostgreSQL database dump
--

\restrict SgUxoL2qhY3XTLK1cFbPpH1TyYdMHwzr7oVeYpsB3TcVbk1CF64eXiwFPw42B9t

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: crebitos_cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crebitos_cliente (
    id bigint NOT NULL,
    limite integer NOT NULL,
    saldo integer NOT NULL
);


--
-- Name: crebitos_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crebitos_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crebitos_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crebitos_transacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crebitos_transacao (
    id bigint NOT NULL,
    valor integer NOT NULL,
    tipo character varying(1) NOT NULL,
    descricao character varying(10) NOT NULL,
    realizada_em timestamp with time zone NOT NULL,
    cliente_id bigint NOT NULL
);


--
-- Name: crebitos_transacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crebitos_transacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crebitos_transacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crebitos_cliente crebitos_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crebitos_cliente
    ADD CONSTRAINT crebitos_cliente_pkey PRIMARY KEY (id);


--
-- Name: crebitos_transacao crebitos_transacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crebitos_transacao
    ADD CONSTRAINT crebitos_transacao_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: idx_transacao_extrato; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transacao_extrato ON public.crebitos_transacao USING btree (cliente_id, id DESC);


--
-- PostgreSQL database dump complete
--

\unrestrict SgUxoL2qhY3XTLK1cFbPpH1TyYdMHwzr7oVeYpsB3TcVbk1CF64eXiwFPw42B9t


-- Marca as migrations como aplicadas: sem isto o Django tentaria criar
-- tabelas que já existem.
--
-- PostgreSQL database dump
--

\restrict Xful1WLHY4auOVnvQSjBN19NruYFLxyGb4JNQHGPxAJhW4G6la44NfQSMUWlpy0

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	crebitos	0001_initial	2026-08-22 01:14:47.557769+00
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 1, true);


--
-- PostgreSQL database dump complete
--

\unrestrict Xful1WLHY4auOVnvQSjBN19NruYFLxyGb4JNQHGPxAJhW4G6la44NfQSMUWlpy0

